import {ExperienceType} from "@/app/page";

export const experiences: ExperienceType[] = [
    {
        id: "ibm",
        title: "IBM",
        role: "Software Development (Co-op)",
        location: "Raleigh",
        locationLink: "https://ibm-zcouncil.com/venues/ibm-rtp/",
        duration:"Incoming Sept 2026",
        description:"",
        icon: "/icons/ibm.png",
        bgIcon: "/icons/ibm_dark.png",
        type:"work",
        bgColor:"#0066ff",
        link:"https://ibm.com"
    },
    {
        id: "hackbeanpot",
        title: "HackBeanpot",
        role: "Software Engineering",
        location: "Boston",
        locationLink: "",
        duration:"Since Apr 2026",
        description:"",
        icon: "/icons/hackbeanpot.png",
        bgIcon: "",
        type:"work",
        bgColor:"#99ccff",
        link:"https://hackbeanpot.com"
    },
    {
        id: "oasis",
        title: "Oasis",
        role: "Software Project Mentor",
        location: "Boston",
        locationLink: "",
        duration:"Since Jan 2026",
        description:"I mentored two groups of students during the semester with their first full-stack projects, giving them weekly advice in our Hack Sessions at all stages of the project development phase - from ideation to development, testing/debugging and production. I helped cover all areas of the tech stack, from backend Node.js and FastAPI with Python to React, HTML, Tailwind CSS, and using JavaScript to manage the DOM, as well as databases using PostgreSQL and some ML frameworks - TensorFlow and scikit-learn.",
        icon: "/icons/oasis.jpg",
        bgIcon: "/icons/oasis_white.png",
        type:"work",
        bgColor:"#336666",
        link:"https://oasisneu.com"
    },
    {
        id: "ta_cs2100",
        title: "Northeastern University",
        role: "CS II Teaching Assistant",
        location: "Boston",
        locationLink: "",
        duration:"Since Jan 2026",
        description:"I ran weekly labs and office hours, helping students with their questions and issues. I also coordinated with the other TA's and staff to develop materials, offer one-on-one tutoring, deliver timely grading, and assist with anything in need. Our semester of CS 2100 featured a brand-new rework of the course in Python using object-oriented programming concepts.",
        icon: "/icons/neu_seal_logo.jpg",
        bgIcon: "",
        type:"work",
        link:"https://neu-pdi.github.io/cs2100-public-resources/"
    },
    {
        id: "ktbyte",
        title: "KTByte Computer Science Academy",
        role: "Teaching Assistant",
        location: "Lexington (MA)",
        locationLink: "",
        duration:"Since 2023",
        description:"Taught students in 1-on-1 settings for all levels of Java as well as block-code.",
        icon: "/icons/ktbyte.png",
        bgIcon: "/icons/ktbyte.png",
        type:"work",
        link:"https://ktbyte.com"
    },
    {
        id: "kumon",
        title: "Kumon",
        role: "Center Assistant",
        location: "Acton (MA)",
        locationLink: "",
        duration:"2021 - 2025",
        description:"At Kumon, I worked 1-on-1 with students of all levels of math and reading skill. I also helped manage the Kumon database and trained new workers, creating materials and giving them a walkthrough of the role for them to work most effectively.",
        icon: "/icons/kumon.png",
        bgIcon: "/icons/kumon_dark.png",
        bgColor:"#373737",
        type:"work",
        link:"https://kumon.com"
    },
    {
        id: "bobabyte",
        title: "BobaByte",
        role: "Lead Organizer",
        location: "Boston",
        locationLink: "",
        duration: "2024 (May - Dec)",
        description: "BobaByte was hosted in Boston as a regional hackathon themed around boba run by some of our team at Hippo Hack along with another group of students passionate about hackathons. In preparation for BobaByte, I finished the main backend functionality and design behind the finished, final state of the hackathon portal, featuring an admin portal for use during the event, live announcement notification system and voting system that could be turned off in the portal, project submission with GitHub and slides link, as well as sign-out and sign-in for users and groups. Despite being remote, I was a key leader in moving tasks along each week and hosting weekly meetings to help deliver the event when the big day came around.",
        icon: "/icons/bobabyte.png",
        bgIcon: "",
        // type:"work",
        link: "https://bobabyte.org",
        type: "work"
    },
    {
        id: "hippohack",
        title: "Hippo Hack",
        role: "Founder, Lead Organizer",
        location: "Boston",
        locationLink: "",
        duration: "2023 - 2024",
        description: "I hosted Hippo Hack with my cousin along with a bunch of other friends where we set out to host a hackathon for younger students as a regional hackathon in our local area. Hosting was very insightful - looking past the deadlines, expenses, and probably some stress, I learned a lot about leading teams, collaborative tools, and hosting big events in general. After pushing back the hackathon date twice, we were able to pull it together towards the end of the summer with 40+ people attending.",
        icon: "/icons/hippohack.png",
        bgIcon: "",
        type: "work",
        link: "https://hippohack.org",
    },
]
